# Segment 1: Data Structures for Algebra

## 1. Scalars

In [17]:
import torch

In [18]:
x = torch.tensor(25)
x

tensor(25)

In [19]:
x.shape

torch.Size([])

## 2. Vectors

In [ ]:
x = torch.tensor([25, 3, 5])
x

tensor([25,  3,  5])

## 3. Matrices

In [ ]:
X = torch.tensor([[25, 2], [5, 26], [12, 3]])
X

tensor([[25,  2],
        [ 5, 26],
        [12,  3]])

In [ ]:
X.shape

torch.Size([3, 2])

In [ ]:
X.size

<function Tensor.size>

In [ ]:
X[:,1]

tensor([ 2, 26,  3])

## 4. Generic Tensor Notation

In [ ]:
# a 4-tensor
images = torch.zeros([32, 28, 28, 3])

In [ ]:
images

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

# **Segment 2: Tensor Operations**

## Tensor Transposition

In [ ]:
x = torch.tensor([[25, 2], [2, 26], [3, 7]])
x

tensor([[25,  2],
        [ 2, 26],
        [ 3,  7]])

In [ ]:
x.T

tensor([[25,  2,  3],
        [ 2, 26,  7]])

## Basic Tensor Arithmetic

In [ ]:
x*2

tensor([[50,  4],
        [ 4, 52],
        [ 6, 14]])

In [ ]:
x+2

tensor([[27,  4],
        [ 4, 28],
        [ 5,  9]])

In [ ]:
x*2+2

tensor([[52,  6],
        [ 6, 54],
        [ 8, 16]])

In [ ]:
torch.add(torch.mul(x, 2), 2)

tensor([[52,  6],
        [ 6, 54],
        [ 8, 16]])

## Hadamard Product or Element-wise Product

In [ ]:
x

tensor([[25,  2],
        [ 2, 26],
        [ 3,  7]])

In [ ]:
A = x + 2
A

tensor([[27,  4],
        [ 4, 28],
        [ 5,  9]])

In [ ]:
A + x

tensor([[52,  6],
        [ 6, 54],
        [ 8, 16]])

In [ ]:
A * x

tensor([[675,   8],
        [  8, 728],
        [ 15,  63]])

## Reduction

In [ ]:
x

tensor([[25,  2],
        [ 2, 26],
        [ 3,  7]])

In [ ]:
torch.sum(x)

tensor(65)

In [ ]:
torch.sum(x, 0)

tensor([30, 35])

In [ ]:
torch.sum(x, 1)

tensor([27, 28, 10])

## The Dot Product

In [ ]:
x = torch.tensor([25, 2, 5])
x

tensor([25,  2,  5])

In [ ]:
y = torch.tensor([0,1,2])
y

tensor([0, 1, 2])

In [ ]:
torch.dot(torch.tensor([25 , 2 , 5.]), torch.tensor([0 , 1 , 2.]))

tensor(12.)

# **Segment 3: Matrix Properties**

## 1. Frobenius Norm

In [ ]:
x = torch.tensor([[2, 2.], [3, 4.]])
x

tensor([[2., 2.],
        [3., 4.]])

In [ ]:
torch.norm(x)

tensor(5.7446)

## 2. Matrix Multiplication

In [ ]:
x = torch.tensor([[3, 4], [5, 6], [7, 8]])
x

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
y = torch.tensor([1, 2])
y

tensor([1, 2])

In [ ]:
torch.matmul(x,y)

tensor([11, 17, 23])

In [ ]:
y = torch.tensor([[1, 9], [2, 0]])
y

tensor([[1, 9],
        [2, 0]])

In [ ]:
torch.matmul(x, y)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [2]:
import numpy as np

In [ ]:
y = np.array([[2,3], [4, 5]])
y

array([[2, 3],
       [4, 5]])

In [ ]:
p = torch.from_numpy(y)
p

tensor([[2, 3],
        [4, 5]])

## 2. Symmetric Matrix

In [3]:
sym = torch.tensor([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
sym

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

In [4]:
sym.T

tensor([[0, 1, 2],
        [1, 7, 8],
        [2, 8, 9]])

In [5]:
sym.T == sym

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 3. Identity Matrix

In [7]:
id = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
id

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [8]:
m = torch.tensor([12, 3, 2])
m

tensor([12,  3,  2])

In [9]:
torch.matmul(id, m)

tensor([12,  3,  2])

## 4. Matrix Inversion

In [12]:
x = torch.tensor([[4, 2], [-5, -3.]])
x

tensor([[ 4.,  2.],
        [-5., -3.]])

In [13]:
x_inv = torch.inverse(x)
x_inv

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [14]:
y = torch.tensor([4, -7.])
y

tensor([ 4., -7.])

In [16]:
w = torch.matmul(x_inv, y)
w

tensor([-1.,  4.])