# Segment 1: Data Structures for Algebra

## Scalars

In [1]:
import tensorflow as tf

In [ ]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [ ]:
x_tf.shape

TensorShape([])

In [ ]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [ ]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [ ]:
tf_sum = tf.add(x_tf , y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [ ]:
tf_sum.numpy()

28

In [ ]:
type(tf_sum.numpy())

numpy.int16

In [ ]:
tf_float = tf.Variable(25. , dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

## Vectors

In [ ]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

## Matrices

In [ ]:
X = tf.Variable([[25, 2], [2, 26], [12, 3]])
X

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 2, 26],
       [12,  3]], dtype=int32)>

In [ ]:
tf.shape(X)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [ ]:
X[:,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, 26,  3], dtype=int32)>

In [ ]:
tf.rank(X)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Generic Tensor Notation

In [ ]:
# a 4-tensor
images = tf.zeros([32, 28, 28, 3])

In [ ]:
images

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   

# **Segment 2: Tensor Operations**

## Tensor Transposition

In [ ]:
x = tf.Variable([[25, 2], [2, 26], [3, 7]])
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 2, 26],
       [ 3,  7]], dtype=int32)>

In [ ]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  2,  3],
       [ 2, 26,  7]], dtype=int32)>

In [ ]:
x*2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[50,  4],
       [ 4, 52],
       [ 6, 14]], dtype=int32)>

In [ ]:
x*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [ 6, 54],
       [ 8, 16]], dtype=int32)>

In [ ]:
tf.add(tf.multiply(x, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [ 6, 54],
       [ 8, 16]], dtype=int32)>

## Hadamard Product or Element-wise Product

In [ ]:
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 2, 26],
       [ 3,  7]], dtype=int32)>

In [ ]:
A = x +2
A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[27,  4],
       [ 4, 28],
       [ 5,  9]], dtype=int32)>

In [ ]:
A +x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [ 6, 54],
       [ 8, 16]], dtype=int32)>

In [ ]:
A * x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [  8, 728],
       [ 15,  63]], dtype=int32)>

## Reduction

In [ ]:
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 2, 26],
       [ 3,  7]], dtype=int32)>

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=65>

In [ ]:
tf.reduce_sum(x, 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 35], dtype=int32)>

In [ ]:
tf.reduce_sum(x,1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 28, 10], dtype=int32)>

## The Dot Product

In [ ]:
x = tf.Variable([25, 2, 5])
x

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [ ]:
y = tf.Variable([0, 1, 2])
y

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [ ]:
tf.reduce_sum(tf.multiply(x,y))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

# **Segment 3: Matrix Properties**

## 1. Frobenius Norm

In [ ]:
x = tf.Variable([[2,2], [3, 4.]])
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
tf.norm(x)

<tf.Tensor: shape=(), dtype=float32, numpy=5.7445626>

## 2. Matrix Multiplication

In [ ]:
x = tf.Variable([[3, 4], [5, 6], [7, 8]])
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
y = tf.Variable([1, 2])
y

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
tf.linalg.matvec(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
y = tf.Variable([[1, 9], [2, 0]])
y

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [ ]:
tf.linalg.matmul(x,y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
y = np.array([[2,4], [3, 5]])
y

array([[2, 4],
       [3, 5]])

In [ ]:
a = tf.convert_to_tensor(y)
a

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [3, 5]])>

## 2. Symmetric Matrix

In [3]:
sym = tf.Variable([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
sym

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]], dtype=int32)>

In [4]:
tf.transpose(sym)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]], dtype=int32)>

In [5]:
tf.transpose(sym) == sym

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

## 3. Identity Matrix

In [7]:
id = tf.Variable([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
id

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

In [8]:
m = tf.Variable([12, 3, 2])
m

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([12,  3,  2], dtype=int32)>

In [11]:
tf.linalg.matvec(id, m)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12,  3,  2], dtype=int32)>

## 4. Matrix Inversion

In [15]:
x = tf.Variable([[4, 2], [-5, -3.]])
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 4.,  2.],
       [-5., -3.]], dtype=float32)>

In [24]:
y = tf.Variable([4, -7.])
y

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([ 4., -7.], dtype=float32)>

In [16]:
x_inv = tf.linalg.inv(x)
x_inv

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

In [25]:
w = tf.linalg.matvec(x_inv, y)